name: aayu_track
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  flutter_markdown_plus: ^0.1.0
  pdf: ^3.10.7
  printing: ^5.13.1
  share_plus: ^12.0.1
  open_filex: ^4.5.0
  animations: ^2.0.11
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.5.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.2
  firebase_core: ^4.2.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/translations/
