name: aayu_track
description: A comprehensive health and wellness tracker powered by AI.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  lottie: ^3.3.2

  health: ^13.2.1
  permission_handler: ^11.3.1
  flutter_reactive_ble: ^5.4.0
  vibration: ^3.1.4

  flutter_markdown: ^0.6.10

  pdf: ^3.10.7
  printing: ^5.13.1
  share_plus: ^12.0.1
  open_filex: ^4.5.0
  path_provider: ^2.1.5

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_local_notifications: ^19.5.0

  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0

  firebase_core: ^4.2.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  analyzer: ^6.4.1
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/

flutter_intl:
  enabled: true
